run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unused-parameter
        severity: warning
