version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  github:
    owner: QYVORA
    name: qyvora-anansi-cli
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
